In [1]:
#import libraries
import numpy as np

In [2]:
#working with numpy array
arr = np.array([40,24,37,45,78,90,50])
print("1D array:", arr)
print("\n Average number:", arr.mean())

1D array: [40 24 37 45 78 90 50]

 Average number: 52.0


In [3]:
#Indexing
print(arr[2])
print(arr[-4])
print(arr[5])


37
45
90


In [4]:
#slicing
print(arr[1:5])
print(arr[:4])
print(arr[9:])
print(arr[-2:-1])
print(arr[8:2])
print(arr[-1:-6])
print(arr[:9])

[24 37 45 78]
[40 24 37 45]
[]
[90]
[]
[]
[40 24 37 45 78 90 50]


In [7]:
#2D array with indexing and slicing
arr2 = np.array([
    [2,3,4],
    [5,6,7],
    [1,8,9]
])

print(arr2)
print(arr2[0,1])
print(arr2[1, :])
print(arr2[1:2, 2])
print(arr2[2, :2])
print(arr2[1:2, 0:2])
                

[[2 3 4]
 [5 6 7]
 [1 8 9]]
3
[5 6 7]
[7]
[1 8]
[[5 6]]


In [9]:
#1D to 2D array
arr3 = np.arange(1,65)
reshape = arr3.reshape(8, 8)
print("Array numbers:",arr3)
print("Reshape 1D array into 2D array:\n", reshape)

flatten = reshape.flatten()
print("Flatten array:", flatten)

Array numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
Reshape 1D array into 2D array:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
Flatten array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
