In [18]:
#import libraries
import numpy as np

In [19]:
#working with numpy array
arr = np.array([40,24,37,45,78,90,50])
print("1D array:", arr)
print("\n Average number:", arr.mean())

1D array: [40 24 37 45 78 90 50]

 Average number: 52.0


In [20]:
#Indexing
print(arr[2])
print(arr[-4])
print(arr[5])


37
45
90


In [21]:
#slicing
print(arr[1:5])
print(arr[:4])
print(arr[9:])
print(arr[-2:-1])
print(arr[8:2])
print(arr[-1:-6])
print(arr[:9])

[24 37 45 78]
[40 24 37 45]
[]
[90]
[]
[]
[40 24 37 45 78 90 50]


In [23]:
#2D array with indexing and slicing
arr2 = np.array([
    [2,3,4],
    [5,6,7],
    [1,8,9]
])

print(arr2)
print(arr2[0,1])
print(arr2[1, :])
print(arr2[1:2, 2])
print(arr2[2, :2])
print(arr2[1:2, 0:2])
                

[[2 3 4]
 [5 6 7]
 [1 8 9]]
3
[5 6 7]
[7]
[1 8]
[[5 6]]


In [24]:
#1D to 2D array
arr3 = np.arange(1,65)
reshape = arr3.reshape(8, 8)
print("Array numbers:",arr3)
print("Reshape 1D array into 2D array:\n", reshape)

flatten = reshape.flatten()
print("Flatten array:", flatten)

Array numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
Reshape 1D array into 2D array:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
Flatten array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


In [26]:
#working with mathematics operation
arr4 = np.array([11,22,33,44,55])
arr5 = np.array([10,20,30,40,50])

#basic math operation
print(arr4 + arr5)
print(arr4 - arr5)
print(arr4 * arr5)
print(arr4 / arr5)

#scaler operation
print(arr5 ** 4)
print(arr5 // 7)
print(arr5 % 9)

[ 21  42  63  84 105]
[1 2 3 4 5]
[ 110  440  990 1760 2750]
[1.1 1.1 1.1 1.1 1.1]
[  10000  160000  810000 2560000 6250000]
[1 2 4 5 7]
[1 2 3 4 5]


In [28]:
#working with dot product
matrix_1 = np.array([
    [5, 2],
    [3, 6]
])

matrix_2 = np.array([
    [9, 4],
    [7, 1]
])

dot_product = np.dot(matrix_1, matrix_2)

multiply_arr = matrix_1 * matrix_2
divide_arr = matrix_1 / matrix_2
print("Dot Product output:\n", dot_product)
print("Multiply arr:", multiply_arr)
print("Divide arr:", divide_arr)

Dot Product output:
 [[59 22]
 [69 18]]
Multiply arr: [[45  8]
 [21  6]]
Divide arr: [[0.55555556 0.5       ]
 [0.42857143 6.        ]]
